Repository sopra-fs25-group-20/sopra-fs25-group-20-client, pull requests merged in 2025-05, with the labels that each got.

#114 Implement Tooltips
  app/components/Settings.tsx
  app/components/Tooltip.tsx
  app/components/chat.tsx
  app/components/dropdown.tsx
  app/components/hud.tsx
  app/styles/layout.css
  app/styles/style.css
Labels: enhancement

#116 Add Error Bar and Prevent Guessing During Voting Phase
  app/components/ErrorBar.tsx
  app/components/gallery.tsx
  app/context/ErrorBarContext.tsx
  app/game/[code]/lobby.tsx
  app/game/[code]/page.tsx
  app/game/[code]/play.tsx
  app/layout.tsx
  app/styles/layout.css
  app/styles/style.css
Labels: front-end

#115 Synchronize Settings Whenever the Component Is Shown
  app/api/gameAPI.ts
  app/components/Settings.tsx
Labels: enhancement

#127 feat:conditional rendering in appheader
  app/components/AppHeader.tsx
Labels: front-end

#128 Apply Token to REST and WebSocket Connections
  app/api/apiService.ts
  app/api/gameAPI.ts
  app/api/stompApi.ts
  app/components/SummaryCard.tsx
  app/components/gallery.tsx
Labels: enhancement

#134 Add Player Profile Page With Profile and Statistics Component
  app/404/page.tsx
  app/components/profileCard.tsx
  app/components/statisticsCard.tsx
  app/not-found.tsx
  app/profile/[username]/page.tsx
  app/profile/page.tsx
  app/styles/layout.css
  app/styles/style.css
Labels: enhancement

#143 Add Contributions for Week 6 [07.05.25 to 13.05.25]
  contributions.md
Labels: documentation

#152 Changing the Timer Setting Does Not Change the Game Settings
  app/components/Settings.tsx
Labels: bug

#154 Route Back to Home When Being Kicked
  app/components/PlayerOverview.tsx
Labels: bug

#155 Kick Button Not Appearing in Summary Phase
  app/components/PlayerOverview.tsx
Labels: bug

#163 Synchronize Game Timer
  app/components/hud.tsx
Labels: bug, front-end

#164 Add Voting Timer
  app/components/hud.tsx
  app/components/voting.tsx
  app/hooks/useCountdownTimer.ts
  app/styles/style.css
Labels: enhancement, front-end

#166 Connection Race Condition
  app/game/[code]/layout.tsx
Labels: bug

#168 Add Button to Profile Which Redirects to Game Setup
  app/components/hud.tsx
  app/components/statisticsCard.tsx
  app/components/voting.tsx
  app/styles/layout.css
Labels: bug, enhancement

#170 Prevent Game From Being Played With Less than Three Players
  app/components/Button.tsx
  app/components/PlayerOverview.tsx
  app/components/Settings.tsx
  app/components/chat.tsx
  app/game/[code]/lobby.tsx
  app/game/[code]/page.tsx
  app/game/[code]/play.tsx
  app/gamesetup/page.tsx
  app/styles/style.css
Labels: bug, enhancement
