Repository sopra-fs25-group-20/sopra-fs25-group-20-client, pull requests merged in 2025-04, with the labels that each got.

#47 Create Game API
  app/api/chat.ts
  app/api/game.ts
  app/api/stompConnection.ts
  app/hooks/useGame.ts
  app/types/account.ts
  app/types/gamePhase.ts
  app/types/gameSettings.ts
  app/types/gameVoteCast.ts
  app/types/gameVoteInit.ts
  app/types/player.ts
Labels: enhancement

#51 Create Game Settings Component
  app/components/Box.tsx
  app/components/InputField.tsx
  app/components/PrimaryButton.tsx
  app/components/chatWindow.tsx
  app/components/dropdown.tsx
  app/components/gameSettingsComponent.tsx
  app/game/[code]/page.tsx
  app/page.tsx
  app/styles/globals.css
Labels: enhancement

#64 Implement Play Page with HUD and Gallery
  app/api/gameAPI.ts
  app/api/stompApi.ts
  app/components/PlayerOverview.tsx
  app/components/Settings.tsx
  app/components/display.tsx
  app/components/gallery.tsx
  app/components/hud.tsx
  app/components/verticalFlex.tsx
  app/game/[code]/play/page.tsx
  app/image/page.tsx
  app/styles/layout.css
  app/styles/style.css
  app/types/gameStart.ts
  app/types/highlightedImage.ts
  app/types/role.ts
Labels: enhancement

#66 Create Voting UI
  app/api/gameAPI.ts
  app/api/stompApi.ts
  app/components/PlayerOverview.tsx
  app/components/Settings.tsx
  app/components/SummaryCard.tsx
  app/components/frame.tsx
  app/components/gallery.tsx
  app/components/hud.tsx
  app/components/verticalFlex.tsx
  app/components/voting.tsx
  app/game/[code]/lobby.tsx
  app/game/[code]/page.tsx
  app/game/[code]/play.tsx
  app/styles/layout.css
  app/types/gameVoteInit.ts
Labels: enhancement, front-end

#67 Create Image Guessing UI for Spy
  app/api/gameAPI.ts
  app/components/SummaryCard.tsx
  app/components/gallery.tsx
  app/game/[code]/play.tsx
  app/styles/layout.css
  app/types/summary.ts
Labels: enhancement, front-end

#77 Disable Option to Change Settings For Non-Admin
  app/components/Settings.tsx
  app/components/dropdown.tsx
  app/styles/style.css
Labels: front-end

#78 Make HUD More Intuitive
  app/components/display.tsx
  app/components/hud.tsx
  app/styles/layout.css
Labels: front-end

#82 fix: persist dark mode across page transitions
  app/context/ThemeContext.tsx
  app/game/[code]/lobby.tsx
  app/layout.tsx
  app/page.tsx
  app/styles/layout.css
Labels: front-end

#83 Refactor Image Guessing for Spy
  app/components/gallery.tsx
  app/game/[code]/play.tsx
  app/styles/style.css
Labels: front-end

#85 Fix Region Options and Change Timer to Seconds
  app/components/Settings.tsx
  app/components/dropdown.tsx
Labels: front-end

#104 Fix Loss of Subscriptions Upon Timeout-Induced Connection Loss
  app/api/stompApi.ts
Labels: front-end
